uses crt, graph;

var  GD, GM : INTEGER;
     C : CHAR;
     X, Y : DOUBLE;
     DIEM : ARRAY[0..1000,0..600] OF BOOLEAN;
     V, G : Real;
     I, J : LONGINT;
     GOC : INTEGER;

PROCEDURE NO;
 VAR I, J : LONGINT;
 BEGIN
  V:=0;

  FOR J:=1 DOWNTO 0 DO
  FOR I:=1 TO 30 DO
   BEGIN
   SETCOLOR(J*14);
   CIRCLE(TRUNC(X),TRUNC(Y),I);
   DELAY(5);
   END;
  FOR I:=TRUNC(X)-30 TO TRUNC(X)+30 DO
   FOR J:=TRUNC(Y)-30 TO TRUNC(Y)+30 DO
    IF (SQR(I-X)+SQR(J-Y)) <= 900 THEN
     DIEM[I,J]:=FALSE;
  X:=500;
  Y:=20;
 END;


PROCEDURE CAU(X,Y : REAL);
 VAR I, J : LONGINT;
 BEGIN
  CIRCLE(TRUNC(X),TRUNC(Y),10);


 END;



BEGIN
 INITGRAPH(GD,GM,'');
 FOR I:=0 TO 1000 DO
  FOR J:=0 TO 600 DO
   DIEM[I,J]:=FALSE;
 FOR I:=0 TO 1000 DO
  FOR J:=400 TO 500 DO
   BEGIN
    PUTPIXEL(I,J,7);
    DIEM[I,J]:=TRUE;
   END;
 X:=500; Y:=20;
 V:=0;
 G:=0;
 GOC:=0;
 REPEAT
  REPEAT
  SETCOLOR(0); CAU(X,Y);
  LINE(500,20,TRUNC(500+100*COS(G*PI/180)),TRUNC(20+100*SIN(G*PI/180)));
   X:=X+V*COS(GOC*PI/180);

   Y:=Y+V*SIN(GOC*PI/180);

  SETCOLOR(7); CAU(X,Y);
  LINE(500,20,TRUNC(500+100*COS(GOC*PI/180)),TRUNC(20+100*SIN(GOC*PI/180)));
  G:=GOC;
  IF Y>500 THEN NO;
  {FOR I:=TRUNC(X)-10 TO TRUNC(X)+10 DO
   FOR J:=TRUNC(Y)-10 TO TRUNC(Y)+10 DO}
    IF DIEM[TRUNC(X),TRUNC(Y)] THEN NO;
  IF DIEM[TRUNC(X),TRUNC(Y)] THEN PUTPIXEL(TRUNC(X),TRUNC(Y),4);
  DELAY(0);
  UNTIL KEYPRESSED;
  C:=READKEY;
  IF C='A' THEN V:=1;
  IF C=#77 THEN GOC:=GOC+1;
  IF C=#75 THEN GOC:=GOC-1;
 UNTIL C='0';

 CLOSEGRAPH;
END.
